---@diagnostic disable: missing-fields, undefined-field
local wezterm = require("wezterm") --[[@as Wezterm]]
local copy = wezterm.action.CopyMode

---@type KeyAssignment[]
return {
	{ key = "Tab", mods = "NONE", action = copy("MoveForwardWord") },
	{ key = "Tab", mods = "SHIFT", action = copy("MoveBackwardWord") },
	{ key = "Enter", mods = "NONE", action = copy("MoveToStartOfNextLine") },
	{ key = "Escape", mods = "NONE", action = copy("Close") },
	{ key = "Space", mods = "NONE", action = copy({ SetSelectionMode = "Cell" }) },
	{ key = "$", mods = "NONE", action = copy("MoveToEndOfLineContent") },
	{ key = "$", mods = "SHIFT", action = copy("MoveToEndOfLineContent") },
	{ key = ",", mods = "NONE", action = copy("JumpReverse") },
	{ key = "0", mods = "NONE", action = copy("MoveToStartOfLine") },
	{ key = ";", mods = "NONE", action = copy("JumpAgain") },
	{ key = "F", mods = "NONE", action = copy({ JumpBackward = { prev_char = false } }) },
	{ key = "F", mods = "SHIFT", action = copy({ JumpBackward = { prev_char = false } }) },
	{ key = "G", mods = "NONE", action = copy("MoveToScrollbackBottom") },
	{ key = "G", mods = "SHIFT", action = copy("MoveToScrollbackBottom") },
	{ key = "H", mods = "NONE", action = copy("MoveToViewportTop") },
	{ key = "H", mods = "SHIFT", action = copy("MoveToViewportTop") },
	{ key = "L", mods = "NONE", action = copy("MoveToViewportBottom") },
	{ key = "L", mods = "SHIFT", action = copy("MoveToViewportBottom") },
	{ key = "M", mods = "NONE", action = copy("MoveToViewportMiddle") },
	{ key = "M", mods = "SHIFT", action = copy("MoveToViewportMiddle") },
	{ key = "O", mods = "NONE", action = copy("MoveToSelectionOtherEndHoriz") },
	{ key = "O", mods = "SHIFT", action = copy("MoveToSelectionOtherEndHoriz") },
	{ key = "T", mods = "NONE", action = copy({ JumpBackward = { prev_char = true } }) },
	{ key = "T", mods = "SHIFT", action = copy({ JumpBackward = { prev_char = true } }) },
	{ key = "V", mods = "NONE", action = copy({ SetSelectionMode = "Line" }) },
	{ key = "V", mods = "SHIFT", action = copy({ SetSelectionMode = "Line" }) },
	{ key = "^", mods = "NONE", action = copy("MoveToStartOfLineContent") },
	{ key = "^", mods = "SHIFT", action = copy("MoveToStartOfLineContent") },
	{ key = "b", mods = "NONE", action = copy("MoveBackwardWord") },
	{ key = "b", mods = "ALT", action = copy("MoveBackwardWord") },
	{ key = "b", mods = "CTRL", action = copy("PageUp") },
	{ key = "c", mods = "CTRL", action = copy("Close") },
	{ key = "d", mods = "CTRL", action = copy({ MoveByPage = 0.5 }) },
	{ key = "e", mods = "NONE", action = copy("MoveForwardWordEnd") },
	{ key = "f", mods = "NONE", action = copy({ JumpForward = { prev_char = false } }) },
	{ key = "f", mods = "ALT", action = copy("MoveForwardWord") },
	{ key = "f", mods = "CTRL", action = copy("PageDown") },
	{ key = "g", mods = "NONE", action = copy("MoveToScrollbackTop") },
	{ key = "g", mods = "CTRL", action = copy("Close") },
	{ key = "h", mods = "NONE", action = copy("MoveLeft") },
	{ key = "j", mods = "NONE", action = copy("MoveDown") },
	{ key = "k", mods = "NONE", action = copy("MoveUp") },
	{ key = "l", mods = "NONE", action = copy("MoveRight") },
	{ key = "m", mods = "ALT", action = copy("MoveToStartOfLineContent") },
	{ key = "o", mods = "NONE", action = copy("MoveToSelectionOtherEnd") },
	{ key = "q", mods = "NONE", action = copy("Close") },
	{ key = "t", mods = "NONE", action = copy({ JumpForward = { prev_char = true } }) },
	{ key = "u", mods = "CTRL", action = copy({ MoveByPage = -0.5 }) },
	{ key = "v", mods = "NONE", action = copy({ SetSelectionMode = "Cell" }) },
	{ key = "v", mods = "CTRL", action = copy({ SetSelectionMode = "Block" }) },
	{ key = "w", mods = "NONE", action = copy("MoveForwardWord") },
	{
		key = "y",
		mods = "NONE",
		action = wezterm.action.Multiple({ { CopyTo = "ClipboardAndPrimarySelection" }, { CopyMode = "Close" } }),
	},
	{ key = "PageUp", mods = "NONE", action = copy("PageUp") },
	{ key = "PageDown", mods = "NONE", action = copy("PageDown") },
	{ key = "End", mods = "NONE", action = copy("MoveToEndOfLineContent") },
	{ key = "Home", mods = "NONE", action = copy("MoveToStartOfLine") },
	{ key = "LeftArrow", mods = "NONE", action = copy("MoveLeft") },
	{ key = "LeftArrow", mods = "ALT", action = copy("MoveBackwardWord") },
	{ key = "RightArrow", mods = "NONE", action = copy("MoveRight") },
	{ key = "RightArrow", mods = "ALT", action = copy("MoveForwardWord") },
	{ key = "UpArrow", mods = "NONE", action = copy("MoveUp") },
	{ key = "DownArrow", mods = "NONE", action = copy("MoveDown") },
}
