#!/bin/sh
# shellcheck source=/dev/null

if [ -n "${ZSH_VERSION}" ]; then
    if [ -s "${HOME}/.zsh_profile" ]; then
        . "${HOME}/.zsh_profile"
    elif [ -s "${HOME}/.zshrc" ]; then
        . "${HOME}/.zshrc"
    else
        . "/etc/profile"
    fi
elif [ -n "${BASH_VERSION}" ]; then
    if [ -s "${HOME}/.bash_profile" ]; then
        . "${HOME}/.bash_profile"
    elif [ -s "${HOME}/.bashrc" ]; then
        . "${HOME}/.bashrc"
    else
        . "/etc/profile"
    fi
fi

[ -d "${HOME}/bin" ] && PATH="${HOME}/bin:${PATH}"
[ -d "${HOME}/.local/bin" ] && PATH="${HOME}/.local/bin:${PATH}"
[ -d "${HOME}/.cargo/bin" ] && PATH="${HOME}/.cargo/bin:${PATH}"
