#!/usr/bin/env bash
# shellcheck source=/dev/null disable=SC2155

export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
export XDG_RUNTIME_DIR="/run/user/${UID}"

[[ "$-" != *"i"* ]] && return

PATH+=":${HOME}/.cargo/bin"
PATH+=":${HOME}/.local/bin"
PATH+=":/usr/local/go/bin"
PATH+=":${HOME}/go/bin"
PATH+=":${HOME}/.yarn/bin"
PATH+=":/opt/nvim"
export PATH

if command -v 'bat' &>/dev/null; then
    export MANPAGER="sh -c 'col -bx | bat --language man --plain'"
    export MANROFFOPT="-c"
elif command -v 'batcat' &>/dev/null; then
    export MANPAGER="sh -c 'col -bx | batcat --language man --plain'"
    export MANROFFOPT="-c"
    alias bat='batcat'
fi

if command -v 'wslinfo' &>/dev/null; then
    export HOST_IS_WSL="1"
fi

export BASH_CONFIG_HOME="${XDG_CONFIG_HOME}/bash"
export BASH_LIB="${BASH_CONFIG_HOME}/lib"
export NVIM_CONFIG_HOME="${XDG_CONFIG_HOME}/nvim"
export SSH_HOME="${HOME}/.ssh"
if [[ -n "${HOST_IS_WSL}" ]]; then
    export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/wsl-ssh-agent.sock"
    source "${BASH_CONFIG_HOME}/tools/ssh.sh"
elif [[ -S "${HOME}/.var/app/com.bitwarden.desktop/data/.bitwarden-ssh-agent.sock" ]]; then
    export SSH_AUTH_SOCK="${HOME}/.var/app/com.bitwarden.desktop/data/.bitwarden-ssh-agent.sock"
    alias bw="flatpak run --command=bw com.bitwarden.desktop"
fi

export HISTSIZE=""
export HISTFILESIZE=""
export HISTCONTROL="ignoreboth:ereasedups"
export HISTIGNORE=$'[\t]*:&:[fb]g:exit'

export EDITOR="nvim"
export FILE_MANAGER="pcmanfm"
export TERM="${TERM:-xterm-256color}"
export BROWSER="librewolf"
export COLORTERM="truecolor"

if [[ -n "${HOST_IS_WSL}" ]]; then
    export FILE_MANAGER="/mnt/c/Windows/explorer.exe"
    export BROWSER="/mnt/c/Program Files/LibreWolf/librewolf.exe"
fi

export LESS="--RAW-CONTROL-CHARS --ignore-case"
export LESS_TERMCAP_mb=$'\e[1;31m'
export LESS_TERMCAP_md=$'\e[1;36m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_so=$'\e[1;44;33m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;32m'
export LESS_TERMCAP_ue=$'\e[0m'

source "${BASH_CONFIG_HOME}/shell.sh"
source "${BASH_CONFIG_HOME}/alias.sh"
source "${BASH_CONFIG_HOME}/functions/bm.sh"
source "${BASH_CONFIG_HOME}/functions/mkcd.sh"
source "${BASH_CONFIG_HOME}/tools/gh.sh"

if [[ -s "${XDG_CONFIG_HOME}/private/bash/config" ]]; then
    source "${XDG_CONFIG_HOME}/private/bash/config"
fi

if [[ -s "${HOME}/.sdkman" ]]; then
    export SDKMAN_DIR="${HOME}/.sdkman"
    source "${SDKMAN_DIR}/bin/sdkman-init.sh"
fi

if [[ -s "${HOME}/.cargo/env" ]]; then
    source "${HOME}/.cargo/env"
fi

if command -v 'starship' &>/dev/null; then
    eval "$(starship init bash)"
else
    PS1="\n\[\e[1;30m\][$$:$PPID - \j:\!\[\e[1;30m\]]\[\e[0;36m\] \T \[\e[1;30m\][\[\e[1;34m\]\u@\H\[\e[1;30m\]:\[\e[0;37m\]${SSH_TTY:-o} \[\e[0;32m\]+${SHLVL}\[\e[1;30m\]] \[\e[1;37m\]\w\[\e[0;37m\] \n\$ "
fi
